---
- hosts: all
  tasks:
  
  - name: Install apache
    yum:
      name: httpd
      state: latest
  
  - name: check httpd service status
    service:
      name: httpd
      state: started

  - name: create user meerim
    user:
      name: meerim
     
  - name: create user nurkyz
    user:
      name: nurkyz
      
      

  - name: create users
    user:
      name: 
        - meerim
        - nurkyz
      
